//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudMap.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessPoints
    {
        public AccessPoints()
        {
            this.Fingerprints = new HashSet<Fingerprints>();
        }
    
        public int Id { get; set; }
        public string MAC { get; set; }
    
        public virtual ICollection<Fingerprints> Fingerprints { get; set; }
    }
}
