//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudMap.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node
    {
        public Node()
        {
            this.EdgeStart = new HashSet<Edge>();
            this.EdgeEnd = new HashSet<Edge>();
        }
    
        public int Id { get; set; }
        public decimal X { get; set; }
        public decimal Y { get; set; }
        public string Floor { get; set; }
    
        public virtual Graph Graph { get; set; }
        public virtual ICollection<Edge> EdgeStart { get; set; }
        public virtual ICollection<Edge> EdgeEnd { get; set; }
        public virtual Floor Floor1 { get; set; }
        public virtual NodeInformation NodeInformation { get; set; }
    }
}
