//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudMap.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nodes
    {
        public Nodes()
        {
            this.Edges = new HashSet<Edges>();
            this.Edges1 = new HashSet<Edges>();
            this.Fingerprints = new HashSet<Fingerprints>();
            this.NodeInformation = new HashSet<NodeInformation>();
        }
    
        public int Id { get; set; }
        public int FloorId { get; set; }
        public decimal X { get; set; }
        public decimal Y { get; set; }
        public System.DateTime CreationTime { get; set; }
    
        public virtual ICollection<Edges> Edges { get; set; }
        public virtual ICollection<Edges> Edges1 { get; set; }
        public virtual ICollection<Fingerprints> Fingerprints { get; set; }
        public virtual Floors Floors { get; set; }
        public virtual ICollection<NodeInformation> NodeInformation { get; set; }
    }
}
