//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudMap.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edges
    {
        public int Id { get; set; }
        public int Graph_Id { get; set; }
        public int NodeStart_Id { get; set; }
        public int EdgeNode1_Edge_Id { get; set; }
    
        public virtual Nodes Nodes { get; set; }
        public virtual Nodes Nodes1 { get; set; }
        public virtual Graphs Graphs { get; set; }
    }
}
