//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudMap.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Floors
    {
        public Floors()
        {
            this.Nodes = new HashSet<Nodes>();
        }
    
        public int Id { get; set; }
        public int MapId { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public System.DateTime CreationTime { get; set; }
    
        public virtual Maps Maps { get; set; }
        public virtual ICollection<Nodes> Nodes { get; set; }
    }
}
