//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudMap.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graph
    {
        public Graph()
        {
            this.Node = new HashSet<Node>();
            this.Edge = new HashSet<Edge>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<Node> Node { get; set; }
        public virtual ICollection<Edge> Edge { get; set; }
        public virtual Map Map { get; set; }
    }
}
