//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudMap.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graphs
    {
        public Graphs()
        {
            this.Edges = new HashSet<Edges>();
            this.Nodes = new HashSet<Nodes>();
            this.Maps = new HashSet<Maps>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<Edges> Edges { get; set; }
        public virtual ICollection<Nodes> Nodes { get; set; }
        public virtual ICollection<Maps> Maps { get; set; }
    }
}
