//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudMap.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map
    {
        public Map()
        {
            this.Floor = new HashSet<Floor>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<Floor> Floor { get; set; }
        public virtual Graph Graph { get; set; }
    }
}
